name: mpchecker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openorb
  - spiceypy
  - numba
  - numpy
  - astropy
  - astroquery
  - requests
  - tqdm
  - pytest
  - pip
  - pip:
      - -e .
